name: Greetings

on:
  push:
    branches:
      - master

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
          issue-message: "We appreciate you pointing us to the problem, and as soon as time allows, we will look into it. Thank you!"
          pr-message: "We appreciate you creating your first pull request and look forward to reviewing your future contributions."
